Add sudoku
st3v3nmw/rust-algorithms pull request #2
Opened 2022-12-17 08:23 UTC by raskovnik

Add sudoku on backtracking algorithm

2022-12-17 16:00 UTC, st3v3nmw requested changes
Looking good so far! Work on the small issues raised

2022-12-17 16:00 UTC, st3v3nmw commented on src/backtracking/sudoku.rs
> +            if board[row][col] == *number {return true;}
For readability, we could have the if as a full block, like return and closing bracket on separate lines

2022-12-17 16:00 UTC, st3v3nmw commented on src/backtracking/sudoku.rs
> +    else {return false;}
Here as well

2022-12-17 16:00 UTC, st3v3nmw commented on src/backtracking/sudoku.rs
> +                       else {return true;}
And here

2022-12-17 16:00 UTC, st3v3nmw commented on src/backtracking/sudoku.rs
> +        assert_eq!(solve(&mut board), false);
You could add 1 more test for a solvable board

2022-12-17 16:10 UTC, st3v3nmw commented on src/backtracking/sudoku.rs
> +        assert_eq!(solve(&mut board), false);
Also, are we able to return the boolean & option<Board>? (False, None) for unsolved boards, & (True, Board) ndo we be able to print later _outside_ the function.

It's still fine of you want that `solve` function to just return the bool

2022-12-19 10:27 UTC, raskovnik commented on src/backtracking/sudoku.rs
> +        assert_eq!(solve(&mut board), false);
it returns the bool but we're modifying the array. We'd just have to iterate over the array to print out the solution

2022-12-19 15:43 UTC, st3v3nmw commented on src/backtracking/sudoku.rs
> +        assert_eq!(solve(&mut board), false);
> it returns the bool but we're modifying the array. We'd just have to iterate over the array to print out the solution

Ah, I see, nice

2022-12-19 15:48 UTC, merged